/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

// AUTO-GENERATED by crates/fuzzer/tools/mir_generator.py.
// rustlantis seed: 192
// Adapted dump calls update the fuzzer crate's global trace state.

#![allow(unused_assignments, unused_parens, overflowing_literals)]

use core::intrinsics::mir::*;
use fuzzer::{dump_var, trace_finish, trace_reset};

#[custom_mir(dialect = "runtime", phase = "initial")]
fn fn1(mut _1: i16, mut _2: u32) -> bool {
    mir! {
        type RET = bool;
        let __rl_dump0: (i16, u32, u64, i16);
        let __rl_dump1: (bool,);
        let _3: u64;
        let _4: i16;
        let _5: f32;
        let _6: bool;
        let _7: isize;
        let _8: isize;
        let _9: ();
        let _10: ();
        {
            RET = false;
            _1 = !(-30222_i16);
            RET = _1 != _1;
            _2 = 2017969765_u32 - 1792978126_u32;
            _1 = '\u{d26c9}' as i16;
            Goto(bb1)
        }
        bb1 = {
            _2 = (-9223372036854775808_isize) as u32;
            RET = _2 > _2;
            Goto(bb2)
        }
        bb2 = {
            _3 = 14779611648837097097_u64 + 13540484398196244491_u64;
            _4 = _1 + _1;
            _6 = RET & RET;
            _6 = RET;
            Goto(bb3)
        }
        bb3 = {
            __rl_dump0 = (Move(_1), Move(_2), Move(_3), Move(_4));
            Call(_9 = dump_var(Move(__rl_dump0)), ReturnTo(bb4), UnwindUnreachable())
        }
        bb4 = {
            __rl_dump1 = (Move(_6),);
            Call(_9 = dump_var(Move(__rl_dump1)), ReturnTo(bb5), UnwindUnreachable())
        }
        bb5 = {
            Return()
        }
    }
}

#[inline(never)]
pub fn compute_rustlantis_trace() -> u64 {
    trace_reset();
    let _ = fn1(1234_i16, 20_u32);
    trace_finish()
}
